### ISSUE TITLE
crash on running and compiling 

### ISSUE THREAD

**Issue by bob-van-der-bibs** [bdkjones/CodeKit-1-Old#318]
as soon  codekit detects a change in a sass of a JS file it compiles and crashes.

using 1.1.1 (6145) 

PS the PAID version...

**Comment by bdkjones** [comment]
Please update to version 1.1.3. The issue has been resolved.

**Comment by bob-van-der-bibs** [comment]
Hi Bryan,

I already updated, so…

1) dont know how you got the crash report
2) once in a while i get
Compass was unable to compile one or more files in the project: 

Errno::ENOENT on line 21 of /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass/cache_stores/filesystem.rb: No such file or directory - /Volumes/Data/Dropbox/projects/_HTMLPROJECTS/filmproducenten/.sass-cache/c64210a40cadcd47f27248556cf3d023d4088f87/_layout.scssc
Run with --trace to see the full backtrace

(This action was triggered by a change to _styles.scss)

3) i don't know what i did before the crash.

**Comment by bob-van-der-bibs** [comment]
Hi Bryan.
i still get an 

Errno::ENOENT on line 26 of /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass/cache_stores/filesystem.rb: No such file or directory - /xxx/xxx/xxx/xxx/_xxx/xxx/.sass-cache/f61a4f2c5ee0218cb5b5659336e44729f4b52d33/_wavs-style.scssc
Run with --trace to see the full backtrace

This only seems to happen on the first compile each subsequent compile runs fine.

**Comment by brendanfalkowski** [comment]
Constantly having this issue. The first compile after changing a partial that was not the last changed partial always fails. I've gotten in the habit of hitting CMD+S twice to avoid it.

My Sass compiles to multiple CSS files, and the OSX notifications whiz by when double-saving so it's not always clear if there was an error in compiling the first one. I have to visibly spot the Codekit log to look out for errors.

This is the output I always see:

```
Compass was unable to compile one or more files in the project: 

Errno::ENOENT on line ["25"] of /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/cache_stores/filesystem.rb: No such file or directory - /Users/brendan/Documents/Work/Clients/xyz/.sass-cache/0a7f67dde99c6f85ae647d87f16a24f103eb1352/_common.scssc
Run with --trace to see the full backtrace

(This action was triggered by a change to _common.scss)
```
